-- 1. HOSPITAL (aucune dépendance)
CREATE TABLE HOSPITAL (
    HOSP_NAME TEXT PRIMARY KEY,
    COUNTRY TEXT,
    ADDRESS TEXT
);

-- 2. MEDICINE (aucune dépendance)
CREATE TABLE MEDICINE (
    REG_NO SERIAL PRIMARY KEY,
    MED_NAME TEXT NOT NULL,
    PRICE NUMERIC(6,3),
    EXP_DATE DATE
);

-- 3. DOCTOR (dépend de HOSPITAL)
CREATE TABLE DOCTOR (
    DOC_ID SERIAL PRIMARY KEY,
    DNAME TEXT,
    GENDER TEXT,
    QUALIFICATION TEXT,
    JOB_SPECIFICATION TEXT,
    HOSP_NAME TEXT REFERENCES HOSPITAL(HOSP_NAME)
);

-- 4. NURSE (dépend de DOCTOR et HOSPITAL)
CREATE TABLE NURSE (
    NURSE_ID SERIAL PRIMARY KEY,
    NAME TEXT,
    GENDER TEXT,
    DOC_ID INTEGER REFERENCES DOCTOR(DOC_ID),
    HOSP_NAME TEXT REFERENCES HOSPITAL(HOSP_NAME)
);

-- 5. RECEPTION (dépend de HOSPITAL)
CREATE TABLE RECEPTION (
    REC_ID SERIAL PRIMARY KEY,
    TEL_NO TEXT NOT NULL,
    EMAIL TEXT,
    HOSP_NAME TEXT REFERENCES HOSPITAL(HOSP_NAME)
);

-- 6. PATIENT (dépend de NURSE et RECEPTION)
CREATE TABLE PATIENT (
    SSN BIGINT PRIMARY KEY,
    FNAME TEXT,
    LNAME TEXT,
    AGE INTEGER,
    GENDER TEXT,
    NURSE_ID INTEGER REFERENCES NURSE(NURSE_ID),
    REC_ID INTEGER REFERENCES RECEPTION(REC_ID)
);

-- 7. APPOINTMENT (dépend de RECEPTION)
CREATE TABLE APPOINTMENT (
    APPOINT_NO SERIAL PRIMARY KEY,
    APPOINT_DATE DATE NOT NULL,
    APPOINT_TIME TIME,
    REC_ID INTEGER REFERENCES RECEPTION(REC_ID)
);

-- 8. DIAGNOSIS (dépend de NURSE et DOCTOR)
CREATE TABLE DIAGNOSIS (
    DIAGNOS_NO SERIAL PRIMARY KEY,
    ISSUE_DATE DATE,
    TREATMENT TEXT,
    REMARKS TEXT,
    NURSE_ID INTEGER REFERENCES NURSE(NURSE_ID),
    DOC_ID INTEGER REFERENCES DOCTOR(DOC_ID)
);

-- 9. VISIT (dépend de PATIENT et HOSPITAL)
CREATE TABLE VISIT (
    VISIT_DATE DATE,
    SSN BIGINT REFERENCES PATIENT(SSN),
    HOSP_NAME TEXT REFERENCES HOSPITAL(HOSP_NAME),
    PRIMARY KEY (VISIT_DATE, SSN)  -- Clé composite recommandée
);

-- 10. PURCHASE (dépend de PATIENT et MEDICINE)
CREATE TABLE PURCHASE (
    SSN BIGINT REFERENCES PATIENT(SSN),
    REG_NO INTEGER REFERENCES MEDICINE(REG_NO),
    PRIMARY KEY (SSN, REG_NO)  -- Clé composite
);

-- 11. EXAMINE (dépend de PATIENT et DOCTOR)
CREATE TABLE EXAMINE (
    SSN BIGINT REFERENCES PATIENT(SSN),
    DOC_ID INTEGER REFERENCES DOCTOR(DOC_ID),
    PRIMARY KEY (SSN, DOC_ID)  -- Clé composite
);

-- 12. MEDICINE_COUNTRY (dépend de MEDICINE)
CREATE TABLE MEDICINE_COUNTRY (
    REG_NO INTEGER REFERENCES MEDICINE(REG_NO),
    MAN_COUNTRY TEXT,
    PRIMARY KEY (REG_NO, MAN_COUNTRY)  -- Clé composite
);